### ISSUE TITLE
Tooltip Does Not Display in Unity Inspector for Serializable Fields

### ISSUE THREAD

**Issue by Long18** [h2v9696/UnityGAS#4]
### **Description:**
When using `[field: Tooltip]` in Unity to display tooltips for serialized fields in custom `ScriptableObject` classes, the tooltip text does appear in the Inspector. The issue can be observed when hovering over the "Current Value Calculator" or "Initial Value Calculator" fields in the Inspector.

### **Expected Behavior:**
The tooltip should appear in Unity's Inspector when hovering over the serialized field, showing the full description provided by the `Tooltip` attribute.

### **Actual Behavior:**
The tooltip does not appear.

### **Unity Version:** 
Tested on Unity 2021.3.X and Unity 2022.1.X.

### **OS:** 
Windows 10 / macOS Ventura

### **Screenshots:**

**Inspector View (No Tooltip Display):**

![Inspector Screenshot](https://github.com/user-attachments/assets/fc96e5c2-5f67-452c-b5a6-35838b23a055)

**Comment by h2v9696** [comment]
Fixed:
https://github.com/h2v9696/UnityGAS/pull/5
